export const MAP_NAMES = {
	NOKIS: "nokis-bazar",
	NOKIS_1_BLOCK: "nokis-bazar-1-block",
	NOKIS_2_BLOCK: "nokis-bazar-2-block",
	NOKIS_3_BLOCK: "nokis-bazar-3-block",
	NOKIS_4_BLOCK: "nokis-bazar-4-block",
	NOKIS_5_BLOCK: "nokis-bazar-5-block",
	NOKIS_6_BLOCK: "nokis-bazar-6-block",
	NOKIS_JAYMA_FILIAL: "nokis-bazar-jayma-filial",
	NOKIS_TAZA_KRITIY: "nokis-bazar-taza-kritiy",
	NOKIS_GONE_KRITIY_1: "nokis-bazar-gone-kritiy-1",
	NOKIS_GONE_KRITIY_2: "nokis-bazar-gone-kritiy-2",

	XOJELI: "xojeli-bazar",
	TAQIYATAS: "taqiyatas-bazar",
	NOKIS_RAYON: "nokis-rayon-bazar",
	KEGEYLI: "kegeyli-bazar",
	XALQABAD: "xalqabad-bazar",
	BOZATAW: "bozataw-bazar",
	QARAOZEK: "qaraozek-bazar",
	TAXTAKOPIR: "taxtakopir-bazar",
	SHIMBAY: "shimbay-bazar",
	SHIMBAY_2: "shimbay-bazar-2",
	QONIRAT: "qonirat-bazar",
	QANLIKOL: "qanlikol-bazar",
	SHOMANAY: "shomanay-bazar",
	BERUNIY: "beruniy-bazar",
	ELLIKQALA: "ellikqala-bazar",
	TORTKUL: "tortkul-bazar",
	AMIWDARYA: "amiwdarya-bazar",
	MOYNAQ: "moynaq-bazar",
} as const

export type MAP_NAMES = (typeof MAP_NAMES)[keyof typeof MAP_NAMES]
