/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LoginImport } from "./routes/login"
import { Route as MapLayoutImport } from "./routes/_map-layout"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as MapLayoutIndexImport } from "./routes/_map-layout/index"
import { Route as MapLayoutUsersImport } from "./routes/_map-layout/users"
import { Route as MapLayoutProfileImport } from "./routes/_map-layout/profile"
import { Route as MapLayoutRestroomsDashboardIndexImport } from "./routes/_map-layout/restrooms-dashboard/index"
import { Route as MapLayoutMarketsDashboardIndexImport } from "./routes/_map-layout/markets-dashboard/index"
import { Route as MapLayoutCarMarketsDashboardIndexImport } from "./routes/_map-layout/car-markets-dashboard/index"
import { Route as GuestPaymentsPaymentIdIndexImport } from "./routes/guest.payments.$paymentId/index"
import { Route as MapLayoutCarMarketsDashboardWantedCarsIndexImport } from "./routes/_map-layout/car-markets-dashboard/wanted-cars/index"
import { Route as MapLayoutCarMarketsDashboardWantedCarsCarIdImport } from "./routes/_map-layout/car-markets-dashboard/wanted-cars/$carId"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutIndexImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/index"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/sell-places"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutRestroomsImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/restrooms"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutProfileImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/profile"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutPaymentsImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/payments"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutParkingImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/parking"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutMapImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/map"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutEmployeesImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/employees"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutDashboardImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/dashboard"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutControlImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/control"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/cattle-market"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutCarMarketImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/car-market"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/employees-payment/index"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/annual-income/index"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/employees-payment/$employeeId"
import { Route as LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateImport } from "./routes/_layout/d.$districtId/m.$marketId/_admin-layout/annual-income/$monthDate"

// Create Virtual Routes

const LayoutDDistrictIdMMarketIdImport = createFileRoute(
  "/_layout/d/$districtId/m/$marketId",
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const MapLayoutRoute = MapLayoutImport.update({
  id: "/_map-layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const MapLayoutIndexRoute = MapLayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MapLayoutRoute,
} as any)

const MapLayoutUsersRoute = MapLayoutUsersImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => MapLayoutRoute,
} as any)

const MapLayoutProfileRoute = MapLayoutProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => MapLayoutRoute,
} as any)

const MapLayoutRestroomsDashboardIndexRoute =
  MapLayoutRestroomsDashboardIndexImport.update({
    id: "/restrooms-dashboard/",
    path: "/restrooms-dashboard/",
    getParentRoute: () => MapLayoutRoute,
  } as any)

const MapLayoutMarketsDashboardIndexRoute =
  MapLayoutMarketsDashboardIndexImport.update({
    id: "/markets-dashboard/",
    path: "/markets-dashboard/",
    getParentRoute: () => MapLayoutRoute,
  } as any)

const MapLayoutCarMarketsDashboardIndexRoute =
  MapLayoutCarMarketsDashboardIndexImport.update({
    id: "/car-markets-dashboard/",
    path: "/car-markets-dashboard/",
    getParentRoute: () => MapLayoutRoute,
  } as any)

const GuestPaymentsPaymentIdIndexRoute =
  GuestPaymentsPaymentIdIndexImport.update({
    id: "/guest/payments/$paymentId/",
    path: "/guest/payments/$paymentId/",
    getParentRoute: () => rootRoute,
  } as any)

const MapLayoutCarMarketsDashboardWantedCarsIndexRoute =
  MapLayoutCarMarketsDashboardWantedCarsIndexImport.update({
    id: "/car-markets-dashboard/wanted-cars/",
    path: "/car-markets-dashboard/wanted-cars/",
    getParentRoute: () => MapLayoutRoute,
  } as any)

const MapLayoutCarMarketsDashboardWantedCarsCarIdRoute =
  MapLayoutCarMarketsDashboardWantedCarsCarIdImport.update({
    id: "/car-markets-dashboard/wanted-cars/$carId",
    path: "/car-markets-dashboard/wanted-cars/$carId",
    getParentRoute: () => MapLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdRoute = LayoutDDistrictIdMMarketIdImport.update(
  {
    id: "/d/$districtId/m/$marketId",
    path: "/d/$districtId/m/$marketId",
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDDistrictIdMMarketIdAdminLayoutRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutImport.update({
    id: "/_admin-layout",
    getParentRoute: () => LayoutDDistrictIdMMarketIdRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutIndexImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesImport.update({
    id: "/sell-places",
    path: "/sell-places",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutRestroomsImport.update({
    id: "/restrooms",
    path: "/restrooms",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutProfileImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutPaymentsImport.update({
    id: "/payments",
    path: "/payments",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutParkingImport.update({
    id: "/parking",
    path: "/parking",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutMapRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutMapImport.update({
    id: "/map",
    path: "/map",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutEmployeesImport.update({
    id: "/employees",
    path: "/employees",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutDashboardImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutControlRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutControlImport.update({
    id: "/control",
    path: "/control",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketImport.update({
    id: "/cattle-market",
    path: "/cattle-market",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutCarMarketImport.update({
    id: "/car-market",
    path: "/car-market",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexImport.update({
    id: "/employees-payment/",
    path: "/employees-payment/",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexImport.update({
    id: "/annual-income/",
    path: "/annual-income/",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdImport.update({
    id: "/employees-payment/$employeeId",
    path: "/employees-payment/$employeeId",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

const LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute =
  LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateImport.update({
    id: "/annual-income/$monthDate",
    path: "/annual-income/$monthDate",
    getParentRoute: () => LayoutDDistrictIdMMarketIdAdminLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/_map-layout": {
      id: "/_map-layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof MapLayoutImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/_map-layout/profile": {
      id: "/_map-layout/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof MapLayoutProfileImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/users": {
      id: "/_map-layout/users"
      path: "/users"
      fullPath: "/users"
      preLoaderRoute: typeof MapLayoutUsersImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/": {
      id: "/_map-layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MapLayoutIndexImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/car-markets-dashboard/": {
      id: "/_map-layout/car-markets-dashboard/"
      path: "/car-markets-dashboard"
      fullPath: "/car-markets-dashboard"
      preLoaderRoute: typeof MapLayoutCarMarketsDashboardIndexImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/markets-dashboard/": {
      id: "/_map-layout/markets-dashboard/"
      path: "/markets-dashboard"
      fullPath: "/markets-dashboard"
      preLoaderRoute: typeof MapLayoutMarketsDashboardIndexImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/restrooms-dashboard/": {
      id: "/_map-layout/restrooms-dashboard/"
      path: "/restrooms-dashboard"
      fullPath: "/restrooms-dashboard"
      preLoaderRoute: typeof MapLayoutRestroomsDashboardIndexImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/car-markets-dashboard/wanted-cars/$carId": {
      id: "/_map-layout/car-markets-dashboard/wanted-cars/$carId"
      path: "/car-markets-dashboard/wanted-cars/$carId"
      fullPath: "/car-markets-dashboard/wanted-cars/$carId"
      preLoaderRoute: typeof MapLayoutCarMarketsDashboardWantedCarsCarIdImport
      parentRoute: typeof MapLayoutImport
    }
    "/_map-layout/car-markets-dashboard/wanted-cars/": {
      id: "/_map-layout/car-markets-dashboard/wanted-cars/"
      path: "/car-markets-dashboard/wanted-cars"
      fullPath: "/car-markets-dashboard/wanted-cars"
      preLoaderRoute: typeof MapLayoutCarMarketsDashboardWantedCarsIndexImport
      parentRoute: typeof MapLayoutImport
    }
    "/guest/payments/$paymentId/": {
      id: "/guest/payments/$paymentId/"
      path: "/guest/payments/$paymentId"
      fullPath: "/guest/payments/$paymentId"
      preLoaderRoute: typeof GuestPaymentsPaymentIdIndexImport
      parentRoute: typeof rootRoute
    }
    "/_layout/d/$districtId/m/$marketId": {
      id: "/_layout/d/$districtId/m/$marketId"
      path: "/d/$districtId/m/$marketId"
      fullPath: "/d/$districtId/m/$marketId"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout"
      path: "/d/$districtId/m/$marketId"
      fullPath: "/d/$districtId/m/$marketId"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdRoute
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/car-market": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/car-market"
      path: "/car-market"
      fullPath: "/d/$districtId/m/$marketId/car-market"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutCarMarketImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/cattle-market": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/cattle-market"
      path: "/cattle-market"
      fullPath: "/d/$districtId/m/$marketId/cattle-market"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/control": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/control"
      path: "/control"
      fullPath: "/d/$districtId/m/$marketId/control"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutControlImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/dashboard": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/dashboard"
      path: "/dashboard"
      fullPath: "/d/$districtId/m/$marketId/dashboard"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutDashboardImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/employees": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/employees"
      path: "/employees"
      fullPath: "/d/$districtId/m/$marketId/employees"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/map": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/map"
      path: "/map"
      fullPath: "/d/$districtId/m/$marketId/map"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutMapImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/parking": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/parking"
      path: "/parking"
      fullPath: "/d/$districtId/m/$marketId/parking"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutParkingImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/payments": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/payments"
      path: "/payments"
      fullPath: "/d/$districtId/m/$marketId/payments"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutPaymentsImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/profile": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/profile"
      path: "/profile"
      fullPath: "/d/$districtId/m/$marketId/profile"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutProfileImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/restrooms": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/restrooms"
      path: "/restrooms"
      fullPath: "/d/$districtId/m/$marketId/restrooms"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutRestroomsImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/sell-places": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/sell-places"
      path: "/sell-places"
      fullPath: "/d/$districtId/m/$marketId/sell-places"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/"
      path: "/"
      fullPath: "/d/$districtId/m/$marketId/"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutIndexImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/$monthDate": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/$monthDate"
      path: "/annual-income/$monthDate"
      fullPath: "/d/$districtId/m/$marketId/annual-income/$monthDate"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/$employeeId": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/$employeeId"
      path: "/employees-payment/$employeeId"
      fullPath: "/d/$districtId/m/$marketId/employees-payment/$employeeId"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/"
      path: "/annual-income"
      fullPath: "/d/$districtId/m/$marketId/annual-income"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
    "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/": {
      id: "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/"
      path: "/employees-payment"
      fullPath: "/d/$districtId/m/$marketId/employees-payment"
      preLoaderRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexImport
      parentRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutDDistrictIdMMarketIdAdminLayoutRouteChildren {
  LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute
  LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute
  LayoutDDistrictIdMMarketIdAdminLayoutControlRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutControlRoute
  LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute
  LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute
  LayoutDDistrictIdMMarketIdAdminLayoutMapRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutMapRoute
  LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute
  LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute
  LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute
  LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute
  LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute
  LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute
  LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute
  LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute
  LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute
  LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute
}

const LayoutDDistrictIdMMarketIdAdminLayoutRouteChildren: LayoutDDistrictIdMMarketIdAdminLayoutRouteChildren =
  {
    LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutControlRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutControlRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutMapRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutMapRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute,
    LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute,
  }

const LayoutDDistrictIdMMarketIdAdminLayoutRouteWithChildren =
  LayoutDDistrictIdMMarketIdAdminLayoutRoute._addFileChildren(
    LayoutDDistrictIdMMarketIdAdminLayoutRouteChildren,
  )

interface LayoutDDistrictIdMMarketIdRouteChildren {
  LayoutDDistrictIdMMarketIdAdminLayoutRoute: typeof LayoutDDistrictIdMMarketIdAdminLayoutRouteWithChildren
}

const LayoutDDistrictIdMMarketIdRouteChildren: LayoutDDistrictIdMMarketIdRouteChildren =
  {
    LayoutDDistrictIdMMarketIdAdminLayoutRoute:
      LayoutDDistrictIdMMarketIdAdminLayoutRouteWithChildren,
  }

const LayoutDDistrictIdMMarketIdRouteWithChildren =
  LayoutDDistrictIdMMarketIdRoute._addFileChildren(
    LayoutDDistrictIdMMarketIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutDDistrictIdMMarketIdRoute: typeof LayoutDDistrictIdMMarketIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDDistrictIdMMarketIdRoute: LayoutDDistrictIdMMarketIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface MapLayoutRouteChildren {
  MapLayoutProfileRoute: typeof MapLayoutProfileRoute
  MapLayoutUsersRoute: typeof MapLayoutUsersRoute
  MapLayoutIndexRoute: typeof MapLayoutIndexRoute
  MapLayoutCarMarketsDashboardIndexRoute: typeof MapLayoutCarMarketsDashboardIndexRoute
  MapLayoutMarketsDashboardIndexRoute: typeof MapLayoutMarketsDashboardIndexRoute
  MapLayoutRestroomsDashboardIndexRoute: typeof MapLayoutRestroomsDashboardIndexRoute
  MapLayoutCarMarketsDashboardWantedCarsCarIdRoute: typeof MapLayoutCarMarketsDashboardWantedCarsCarIdRoute
  MapLayoutCarMarketsDashboardWantedCarsIndexRoute: typeof MapLayoutCarMarketsDashboardWantedCarsIndexRoute
}

const MapLayoutRouteChildren: MapLayoutRouteChildren = {
  MapLayoutProfileRoute: MapLayoutProfileRoute,
  MapLayoutUsersRoute: MapLayoutUsersRoute,
  MapLayoutIndexRoute: MapLayoutIndexRoute,
  MapLayoutCarMarketsDashboardIndexRoute:
    MapLayoutCarMarketsDashboardIndexRoute,
  MapLayoutMarketsDashboardIndexRoute: MapLayoutMarketsDashboardIndexRoute,
  MapLayoutRestroomsDashboardIndexRoute: MapLayoutRestroomsDashboardIndexRoute,
  MapLayoutCarMarketsDashboardWantedCarsCarIdRoute:
    MapLayoutCarMarketsDashboardWantedCarsCarIdRoute,
  MapLayoutCarMarketsDashboardWantedCarsIndexRoute:
    MapLayoutCarMarketsDashboardWantedCarsIndexRoute,
}

const MapLayoutRouteWithChildren = MapLayoutRoute._addFileChildren(
  MapLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  "": typeof MapLayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/profile": typeof MapLayoutProfileRoute
  "/users": typeof MapLayoutUsersRoute
  "/": typeof MapLayoutIndexRoute
  "/car-markets-dashboard": typeof MapLayoutCarMarketsDashboardIndexRoute
  "/markets-dashboard": typeof MapLayoutMarketsDashboardIndexRoute
  "/restrooms-dashboard": typeof MapLayoutRestroomsDashboardIndexRoute
  "/car-markets-dashboard/wanted-cars/$carId": typeof MapLayoutCarMarketsDashboardWantedCarsCarIdRoute
  "/car-markets-dashboard/wanted-cars": typeof MapLayoutCarMarketsDashboardWantedCarsIndexRoute
  "/guest/payments/$paymentId": typeof GuestPaymentsPaymentIdIndexRoute
  "/d/$districtId/m/$marketId": typeof LayoutDDistrictIdMMarketIdAdminLayoutRouteWithChildren
  "/d/$districtId/m/$marketId/car-market": typeof LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute
  "/d/$districtId/m/$marketId/cattle-market": typeof LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute
  "/d/$districtId/m/$marketId/control": typeof LayoutDDistrictIdMMarketIdAdminLayoutControlRoute
  "/d/$districtId/m/$marketId/dashboard": typeof LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute
  "/d/$districtId/m/$marketId/employees": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute
  "/d/$districtId/m/$marketId/map": typeof LayoutDDistrictIdMMarketIdAdminLayoutMapRoute
  "/d/$districtId/m/$marketId/parking": typeof LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute
  "/d/$districtId/m/$marketId/payments": typeof LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute
  "/d/$districtId/m/$marketId/profile": typeof LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute
  "/d/$districtId/m/$marketId/restrooms": typeof LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute
  "/d/$districtId/m/$marketId/sell-places": typeof LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute
  "/d/$districtId/m/$marketId/": typeof LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute
  "/d/$districtId/m/$marketId/annual-income/$monthDate": typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute
  "/d/$districtId/m/$marketId/employees-payment/$employeeId": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute
  "/d/$districtId/m/$marketId/annual-income": typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute
  "/d/$districtId/m/$marketId/employees-payment": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute
}

export interface FileRoutesByTo {
  "": typeof LayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/profile": typeof MapLayoutProfileRoute
  "/users": typeof MapLayoutUsersRoute
  "/": typeof MapLayoutIndexRoute
  "/car-markets-dashboard": typeof MapLayoutCarMarketsDashboardIndexRoute
  "/markets-dashboard": typeof MapLayoutMarketsDashboardIndexRoute
  "/restrooms-dashboard": typeof MapLayoutRestroomsDashboardIndexRoute
  "/car-markets-dashboard/wanted-cars/$carId": typeof MapLayoutCarMarketsDashboardWantedCarsCarIdRoute
  "/car-markets-dashboard/wanted-cars": typeof MapLayoutCarMarketsDashboardWantedCarsIndexRoute
  "/guest/payments/$paymentId": typeof GuestPaymentsPaymentIdIndexRoute
  "/d/$districtId/m/$marketId": typeof LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute
  "/d/$districtId/m/$marketId/car-market": typeof LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute
  "/d/$districtId/m/$marketId/cattle-market": typeof LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute
  "/d/$districtId/m/$marketId/control": typeof LayoutDDistrictIdMMarketIdAdminLayoutControlRoute
  "/d/$districtId/m/$marketId/dashboard": typeof LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute
  "/d/$districtId/m/$marketId/employees": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute
  "/d/$districtId/m/$marketId/map": typeof LayoutDDistrictIdMMarketIdAdminLayoutMapRoute
  "/d/$districtId/m/$marketId/parking": typeof LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute
  "/d/$districtId/m/$marketId/payments": typeof LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute
  "/d/$districtId/m/$marketId/profile": typeof LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute
  "/d/$districtId/m/$marketId/restrooms": typeof LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute
  "/d/$districtId/m/$marketId/sell-places": typeof LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute
  "/d/$districtId/m/$marketId/annual-income/$monthDate": typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute
  "/d/$districtId/m/$marketId/employees-payment/$employeeId": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute
  "/d/$districtId/m/$marketId/annual-income": typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute
  "/d/$districtId/m/$marketId/employees-payment": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/_map-layout": typeof MapLayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/_map-layout/profile": typeof MapLayoutProfileRoute
  "/_map-layout/users": typeof MapLayoutUsersRoute
  "/_map-layout/": typeof MapLayoutIndexRoute
  "/_map-layout/car-markets-dashboard/": typeof MapLayoutCarMarketsDashboardIndexRoute
  "/_map-layout/markets-dashboard/": typeof MapLayoutMarketsDashboardIndexRoute
  "/_map-layout/restrooms-dashboard/": typeof MapLayoutRestroomsDashboardIndexRoute
  "/_map-layout/car-markets-dashboard/wanted-cars/$carId": typeof MapLayoutCarMarketsDashboardWantedCarsCarIdRoute
  "/_map-layout/car-markets-dashboard/wanted-cars/": typeof MapLayoutCarMarketsDashboardWantedCarsIndexRoute
  "/guest/payments/$paymentId/": typeof GuestPaymentsPaymentIdIndexRoute
  "/_layout/d/$districtId/m/$marketId": typeof LayoutDDistrictIdMMarketIdRouteWithChildren
  "/_layout/d/$districtId/m/$marketId/_admin-layout": typeof LayoutDDistrictIdMMarketIdAdminLayoutRouteWithChildren
  "/_layout/d/$districtId/m/$marketId/_admin-layout/car-market": typeof LayoutDDistrictIdMMarketIdAdminLayoutCarMarketRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/cattle-market": typeof LayoutDDistrictIdMMarketIdAdminLayoutCattleMarketRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/control": typeof LayoutDDistrictIdMMarketIdAdminLayoutControlRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/dashboard": typeof LayoutDDistrictIdMMarketIdAdminLayoutDashboardRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/employees": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/map": typeof LayoutDDistrictIdMMarketIdAdminLayoutMapRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/parking": typeof LayoutDDistrictIdMMarketIdAdminLayoutParkingRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/payments": typeof LayoutDDistrictIdMMarketIdAdminLayoutPaymentsRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/profile": typeof LayoutDDistrictIdMMarketIdAdminLayoutProfileRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/restrooms": typeof LayoutDDistrictIdMMarketIdAdminLayoutRestroomsRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/sell-places": typeof LayoutDDistrictIdMMarketIdAdminLayoutSellPlacesRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/": typeof LayoutDDistrictIdMMarketIdAdminLayoutIndexRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/$monthDate": typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeMonthDateRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/$employeeId": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentEmployeeIdRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/": typeof LayoutDDistrictIdMMarketIdAdminLayoutAnnualIncomeIndexRoute
  "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/": typeof LayoutDDistrictIdMMarketIdAdminLayoutEmployeesPaymentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/login"
    | "/profile"
    | "/users"
    | "/"
    | "/car-markets-dashboard"
    | "/markets-dashboard"
    | "/restrooms-dashboard"
    | "/car-markets-dashboard/wanted-cars/$carId"
    | "/car-markets-dashboard/wanted-cars"
    | "/guest/payments/$paymentId"
    | "/d/$districtId/m/$marketId"
    | "/d/$districtId/m/$marketId/car-market"
    | "/d/$districtId/m/$marketId/cattle-market"
    | "/d/$districtId/m/$marketId/control"
    | "/d/$districtId/m/$marketId/dashboard"
    | "/d/$districtId/m/$marketId/employees"
    | "/d/$districtId/m/$marketId/map"
    | "/d/$districtId/m/$marketId/parking"
    | "/d/$districtId/m/$marketId/payments"
    | "/d/$districtId/m/$marketId/profile"
    | "/d/$districtId/m/$marketId/restrooms"
    | "/d/$districtId/m/$marketId/sell-places"
    | "/d/$districtId/m/$marketId/"
    | "/d/$districtId/m/$marketId/annual-income/$monthDate"
    | "/d/$districtId/m/$marketId/employees-payment/$employeeId"
    | "/d/$districtId/m/$marketId/annual-income"
    | "/d/$districtId/m/$marketId/employees-payment"
  fileRoutesByTo: FileRoutesByTo
  to:
    | ""
    | "/login"
    | "/profile"
    | "/users"
    | "/"
    | "/car-markets-dashboard"
    | "/markets-dashboard"
    | "/restrooms-dashboard"
    | "/car-markets-dashboard/wanted-cars/$carId"
    | "/car-markets-dashboard/wanted-cars"
    | "/guest/payments/$paymentId"
    | "/d/$districtId/m/$marketId"
    | "/d/$districtId/m/$marketId/car-market"
    | "/d/$districtId/m/$marketId/cattle-market"
    | "/d/$districtId/m/$marketId/control"
    | "/d/$districtId/m/$marketId/dashboard"
    | "/d/$districtId/m/$marketId/employees"
    | "/d/$districtId/m/$marketId/map"
    | "/d/$districtId/m/$marketId/parking"
    | "/d/$districtId/m/$marketId/payments"
    | "/d/$districtId/m/$marketId/profile"
    | "/d/$districtId/m/$marketId/restrooms"
    | "/d/$districtId/m/$marketId/sell-places"
    | "/d/$districtId/m/$marketId/annual-income/$monthDate"
    | "/d/$districtId/m/$marketId/employees-payment/$employeeId"
    | "/d/$districtId/m/$marketId/annual-income"
    | "/d/$districtId/m/$marketId/employees-payment"
  id:
    | "__root__"
    | "/_layout"
    | "/_map-layout"
    | "/login"
    | "/_map-layout/profile"
    | "/_map-layout/users"
    | "/_map-layout/"
    | "/_map-layout/car-markets-dashboard/"
    | "/_map-layout/markets-dashboard/"
    | "/_map-layout/restrooms-dashboard/"
    | "/_map-layout/car-markets-dashboard/wanted-cars/$carId"
    | "/_map-layout/car-markets-dashboard/wanted-cars/"
    | "/guest/payments/$paymentId/"
    | "/_layout/d/$districtId/m/$marketId"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/car-market"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/cattle-market"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/control"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/dashboard"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/employees"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/map"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/parking"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/payments"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/profile"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/restrooms"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/sell-places"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/$monthDate"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/$employeeId"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/"
    | "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  MapLayoutRoute: typeof MapLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  GuestPaymentsPaymentIdIndexRoute: typeof GuestPaymentsPaymentIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  MapLayoutRoute: MapLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  GuestPaymentsPaymentIdIndexRoute: GuestPaymentsPaymentIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/_map-layout",
        "/login",
        "/guest/payments/$paymentId/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/d/$districtId/m/$marketId"
      ]
    },
    "/_map-layout": {
      "filePath": "_map-layout.tsx",
      "children": [
        "/_map-layout/profile",
        "/_map-layout/users",
        "/_map-layout/",
        "/_map-layout/car-markets-dashboard/",
        "/_map-layout/markets-dashboard/",
        "/_map-layout/restrooms-dashboard/",
        "/_map-layout/car-markets-dashboard/wanted-cars/$carId",
        "/_map-layout/car-markets-dashboard/wanted-cars/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_map-layout/profile": {
      "filePath": "_map-layout/profile.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/users": {
      "filePath": "_map-layout/users.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/": {
      "filePath": "_map-layout/index.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/car-markets-dashboard/": {
      "filePath": "_map-layout/car-markets-dashboard/index.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/markets-dashboard/": {
      "filePath": "_map-layout/markets-dashboard/index.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/restrooms-dashboard/": {
      "filePath": "_map-layout/restrooms-dashboard/index.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/car-markets-dashboard/wanted-cars/$carId": {
      "filePath": "_map-layout/car-markets-dashboard/wanted-cars/$carId.tsx",
      "parent": "/_map-layout"
    },
    "/_map-layout/car-markets-dashboard/wanted-cars/": {
      "filePath": "_map-layout/car-markets-dashboard/wanted-cars/index.tsx",
      "parent": "/_map-layout"
    },
    "/guest/payments/$paymentId/": {
      "filePath": "guest.payments.$paymentId/index.tsx"
    },
    "/_layout/d/$districtId/m/$marketId": {
      "filePath": "_layout/d.$districtId/m.$marketId",
      "parent": "/_layout",
      "children": [
        "/_layout/d/$districtId/m/$marketId/_admin-layout"
      ]
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId",
      "children": [
        "/_layout/d/$districtId/m/$marketId/_admin-layout/car-market",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/cattle-market",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/control",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/dashboard",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/employees",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/map",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/parking",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/payments",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/profile",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/restrooms",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/sell-places",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/$monthDate",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/$employeeId",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/",
        "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/"
      ]
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/car-market": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/car-market.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/cattle-market": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/cattle-market.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/control": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/control.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/dashboard": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/dashboard.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/employees": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/employees.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/map": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/map.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/parking": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/parking.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/payments": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/payments.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/profile": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/profile.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/restrooms": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/restrooms.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/sell-places": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/sell-places.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/index.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/$monthDate": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/annual-income/$monthDate.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/$employeeId": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/employees-payment/$employeeId.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/annual-income/": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/annual-income/index.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    },
    "/_layout/d/$districtId/m/$marketId/_admin-layout/employees-payment/": {
      "filePath": "_layout/d.$districtId/m.$marketId/_admin-layout/employees-payment/index.tsx",
      "parent": "/_layout/d/$districtId/m/$marketId/_admin-layout"
    }
  }
}
ROUTE_MANIFEST_END */
